### PR TITLE
Adding a new type of pad: Math!

### PR DESCRIPTION
**Pull request by nicola**
Equation lovers, this PR is for you!

- I have added a new type of pad called `Math pad`. This supports basic latex via `KaTex`!
- There is now support for `$E = mc^2$` (inline) and `$$y=f(x)$$` (block).
- It works in preview as well!

This PR will only work if the PR on https://github.com/ipfs-shipyard/peerpad-core/pull/2

Related links:
- [Pad with some examples](https://gateway.ipfs.io/ipfs/QmbgcTxNdVnFk4wsvxnovugRXBX8NsiqNBoiv1nVUJhLva/index.html#/w/math/SP8B6HwHQFRpknFbTSxBvA/4XTTM6TKdN4C8g4j7bcoh1M8tQdVbmbr9HFcJ6hhE85MEFTrj/K3TgUEgELeNmzdWrsvRpPbsQuUKzEAwGcHmeFckE2B6yyrsWsJ18aZkrffdgNcqzngqm6GKEbwWzp9uh5WPRi59bhMsv8feYeeK6txSvKxtKkCeTDSZLrQ62b3YdjdDKJpsz46y1)
- [Peerpad with the PR](https://gateway.ipfs.io/ipfs/QmbgcTxNdVnFk4wsvxnovugRXBX8NsiqNBoiv1nVUJhLva/index.html)!

---

Note: this PR is hacky and doesn't have tests :(

### CODE REVIEW

**Comment by nicola** [comment]
For some reasons the one on localhost works smoothly, not the one on ipfs :(

**Comment by pgte** [comment]
Depends on https://github.com/ipfs-shipyard/peerpad-core/issues/3, provided in peerpad-core@v0.6.1

**Comment by pgte** [comment]
@nicola ❤️

localhost_3000___w_math_dljz644pu3hv6dpyegkiea_4xttme6y5cbsyxv8s5uufymudnzpoucdamqjqepcevjdk1diz_k3tgueavuqoi2crmg7xcycvdmztkyowheyc95na5g5rpy9m8syum7a3hpp93fwqb1t6y3kekcwu1bupmhekfnf4luxru9thfvnpsvugc4v46fwd3xva2ikppaczeqy2mbfqtrfdt

**Comment by nicola** [comment]
OMG I made it into master!

**Comment by olizilla** [comment]
:shipit: ✨   Very cool

**Comment by diasdavid** [comment]
@nicola  Seems that the Math pad supports markdown + math. Couldn't this be the same as the Markdown pad?

**Comment by nicola** [comment]
@diasdavid it could!

The only issue is that technically they are not the same and people would have to escape `$` if they use them!

**Pull request merged**
