### PR TITLE
Configures markdown mode and styles syntax

### PR DESCRIPTION
**Pull request by alanshaw**
screen shot 2017-10-20 at 10 25 33

### CODE REVIEW

**Comment by diasdavid** [comment]
@alanshaw is there a way you can make the markdown be github markdown?

**Comment by alanshaw** [comment]
um, I'm not sure I understand...do you mean when it's rendered?

**Comment by diasdavid** [comment]
@alanshaw exactly. Github markdown picks up in some nice things like line breaks translate to paragraphs

**Comment by alanshaw** [comment]
Looks like this is on by default:
https://github.com/wooorm/remark/tree/master/packages/remark-parse#optionsgfm

Doesn't look like line breaks -> paragraphs is part of it though 😞

**Comment by olizilla** [comment]
👁

**Pull request merged**
