### PR TITLE
Disabled missing features, move network status

### LINKED ISSUE #55: Disable non implemented UI elements
Such as:

image

and 
image

### LINKED ISSUE #57: Move IPFS node status up and make writing area bigger
image

### PR DESCRIPTION
**Pull request by olizilla**
Fix #55 - Disable non-implemented UI features
Fix #57 - move IPFS node status up to header and make writing area bigger

screenshot 2017-10-25 17 04 00

### CODE REVIEW

**Comment by alanshaw** [comment]
This is mostly great, but it feels odd that the edit side scrolls when you exceed the available space but the preview side doesn't. IMHO a min-height on the editor would be better so that we only have one scroller on the page - the page itself.

screen shot 2017-10-26 at 09 36 44

**Comment by alanshaw** [comment]
Also, I figured the `+` icon in the header made a new document, which I thought would be pretty easy to implement - it looks a bit empty up there atm...

**Comment by olizilla** [comment]
@alanshaw `+` icon is for adding collaborators, and I've no idea how that'd work. Can you coerce a peer into syndicating your pad without all being on a p2p notification mesh? Perhaps a follow pad request via secure-scuttlebutt... who knows.

**Comment by olizilla** [comment]
@alanshaw i'll take another look at the height thing. With height set to auto, I was having trouble with Codemirror's custom scrollbars, and the editor visibly resizing a few seconds after page load which was kind of jarring. I can probs make it better tho. 👍

**Comment by olizilla** [comment]
@alanshaw quite right you were. I've simplified the scrolling back to as you had it and it feels nice.

of note, the codemirror docs warn that:

> `viewportMargin` can be set to Infinity to make sure the whole document is always rendered, and thus the browser's text search works on it. This will have bad effects on performance of big documents."

http://codemirror.net/doc/manual.html#option_viewportMargin

So at some point a smart, scroll sync'd editor/preview thinger that can elect to only render the slice of doc in view may be needed, but what we have is plenty good enough for now.

I've added `autofocus: true` for nice user feels, and set `inputStyle: contenteditable` as the docs suggest that is the good one (https://codemirror.net/doc/manual.html#option_inputStyle)

**Pull request merged**
